### ISSUE TITLE
MD: Adding and removing some features In responder module 

### ISSUE THREAD

**Issue by Joshua0nio** [fastline21/OneTapAlertFFEMobile#2]
- On the part of viewing resident info, the resident info should be specific put it in a box that all the information of the user and put at the top of the information a "Resident Information".
- respond button, should have a popup display that have confirmation if the responder want to respond
- On the map, add a text at the top that shows the location of the resident in text 
- on respond page, remove the description, the data should be straight to the admin

**Comment by fastline21** [comment]
Emergency Screen
<img src="https://user-images.githubusercontent.com/19354682/219870030-ab83b931-dd9f-4eaf-a61d-eeb66167b670.png" width="300">
